#!/bin/sh

# Set these paths appropriately

# For Windows, these should be Windows paths with backslashes (which will need
# single-quoting), not Cygwin-style paths, e.g.
# BIN='C:\TreeTagger\bin'
# The script will probably fail if the BIN or LIB directory names contain
# spaces.  You should install the tree tagger in a directory that does not
# contain spaces in its path (i.e. not under "Program Files").

BIN=/usr/local/durmtools/TreeTagger/bin
CMD=/usr/local/durmtools/TreeTagger/cmd
LIB=/usr/local/durmtools/TreeTagger/lib

GERMANTAGGER=${CMD}/tree-tagger-german
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-chunker.par

$GERMANTAGGER $* |
perl -nae 'if ($#F==0){print}else{print "$F[0]-$F[1]\n"}' |
$TAGGER $PARFILE -token -sgml -eps 0.00000001 -quiet
