package genes.models.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-05T11:07:54.908+01:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "GeneToolsService", 
                  wsdlLocation = "http://pingu.unige.ch:8080/NormaGene/GeneTools?wsdl",
                  targetNamespace = "http://ws.models.genes/") 
public class GeneToolsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.models.genes/", "GeneToolsService");
    public final static QName GeneToolsPort = new QName("http://ws.models.genes/", "GeneToolsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://pingu.unige.ch:8080/NormaGene/GeneTools?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GeneToolsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://pingu.unige.ch:8080/NormaGene/GeneTools?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GeneToolsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GeneToolsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneToolsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GeneTools
     */
    @WebEndpoint(name = "GeneToolsPort")
    public GeneTools getGeneToolsPort() {
        return super.getPort(GeneToolsPort, GeneTools.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeneTools
     */
    @WebEndpoint(name = "GeneToolsPort")
    public GeneTools getGeneToolsPort(WebServiceFeature... features) {
        return super.getPort(GeneToolsPort, GeneTools.class, features);
    }

}
