package genes.models.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-05T11:07:54.899+01:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://ws.models.genes/", name = "GeneTools")
@XmlSeeAlso({ObjectFactory.class})
public interface GeneTools {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.models.genes/GeneTools/getBioCreativeResultsRequest", output = "http://ws.models.genes/GeneTools/getBioCreativeResultsResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://ws.models.genes/GeneTools/getBioCreativeResults/Fault/IOException")})
    @RequestWrapper(localName = "getBioCreativeResults", targetNamespace = "http://ws.models.genes/", className = "genes.models.ws.GetBioCreativeResults")
    @WebMethod
    @ResponseWrapper(localName = "getBioCreativeResultsResponse", targetNamespace = "http://ws.models.genes/", className = "genes.models.ws.GetBioCreativeResultsResponse")
    public genes.models.ws.MyMap getBioCreativeResults(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text,
        @WebParam(name = "goCat", targetNamespace = "")
        boolean goCat,
        @WebParam(name = "thresh", targetNamespace = "")
        double thresh
    ) throws IOException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.models.genes/GeneTools/getGenesTaggerRequest", output = "http://ws.models.genes/GeneTools/getGenesTaggerResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://ws.models.genes/GeneTools/getGenesTagger/Fault/IOException")})
    @RequestWrapper(localName = "getGenesTagger", targetNamespace = "http://ws.models.genes/", className = "genes.models.ws.GetGenesTagger")
    @WebMethod
    @ResponseWrapper(localName = "getGenesTaggerResponse", targetNamespace = "http://ws.models.genes/", className = "genes.models.ws.GetGenesTaggerResponse")
    public java.lang.String getGenesTagger(
        @WebParam(name = "txt", targetNamespace = "")
        java.lang.String txt,
        @WebParam(name = "thresh", targetNamespace = "")
        double thresh
    ) throws IOException_Exception;
}
