
package genes.models.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-05T11:07:54.890+01:00
 * Generated source version: 2.4.1
 */

@WebFault(name = "IOException", targetNamespace = "http://ws.models.genes/")
public class IOException_Exception extends Exception {
    
    private genes.models.ws.IOException ioException;

    public IOException_Exception() {
        super();
    }
    
    public IOException_Exception(String message) {
        super(message);
    }
    
    public IOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, genes.models.ws.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, genes.models.ws.IOException ioException, Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public genes.models.ws.IOException getFaultInfo() {
        return this.ioException;
    }
}
